import {desktop} from './desktop';
export type Box = {x:number;y:number;w:number;h:number;label:string};
export type Asset = {id:string;name:string;src:string;label:string;boxes:Box[];split?:string};
export type Project = {id:string;name:string;type:'classify'|'detect';description:string;created:string;labels:string[];assets:Asset[];step:number;models:any[];history:any[]};
export async function readProjects():Promise<Project[]> { if(desktop())return desktop().readProjects(); const db=await open();return new Promise((resolve,reject)=>{const r=db.transaction('state').objectStore('state').get('projects');r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error);}); }
export async function saveProjects(p:Project[]) {if(desktop())return desktop().saveProjects(p);const db=await open();return new Promise<void>((resolve,reject)=>{const t=db.transaction('state','readwrite');t.objectStore('state').put(p,'projects');t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);});}
function open():Promise<IDBDatabase> {return new Promise((resolve,reject)=>{const r=indexedDB.open('zhixing-lab',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export function makeProject(name:string,type:'classify'|'detect',description=''):Project {return {id:crypto.randomUUID(),name,type,description,created:new Date().toISOString(),labels:['前进','左转','右转','停车'],assets:[],step:0,models:[],history:[]};}
export function splitAssets(assets:Asset[],train=70,val=20,seed=42) {let s=seed;const shuffled=[...assets].sort((a,b)=>a.id.localeCompare(b.id));for(let i=shuffled.length-1;i>0;i--){s=(s*1664525+1013904223)>>>0;const j=s%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}return shuffled.map((a,i)=>({...a,split:i<Math.floor(assets.length*train/100)?'训练集':i<Math.floor(assets.length*(train+val)/100)?'验证集':'测试集'}));}
export function download(name:string,data:any) {const url=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
